#ifndef gdcm_expat_mangle_h
#define gdcm_expat_mangle_h

/*

This header file mangles all symbols exported from the expat library.
It is included in all files while building the expat library.  Due to
namespace pollution, no expat headers should be included in .h files in
VTK.

The following command was used to obtain the symbol list:

nm libgdcmexpat.a |grep " [TR] "

*/

#define asParser gdcm_expat_asParser 
#define XML_DefaultCurrent gdcm_expat_XML_DefaultCurrent
#define XML_ErrorString gdcm_expat_XML_ErrorString
#define XML_ExpatVersion gdcm_expat_XML_ExpatVersion
#define XML_ExpatVersionInfo gdcm_expat_XML_ExpatVersionInfo
#define XML_ExternalEntityParserCreate gdcm_expat_XML_ExternalEntityParserCreate
#define XML_GetBase gdcm_expat_XML_GetBase
#define XML_GetBuffer gdcm_expat_XML_GetBuffer
#define XML_GetCurrentByteCount gdcm_expat_XML_GetCurrentByteCount
#define XML_GetCurrentByteIndex gdcm_expat_XML_GetCurrentByteIndex
#define XML_GetCurrentColumnNumber gdcm_expat_XML_GetCurrentColumnNumber
#define XML_GetCurrentLineNumber gdcm_expat_XML_GetCurrentLineNumber
#define XML_GetErrorCode gdcm_expat_XML_GetErrorCode
#define XML_GetIdAttributeIndex gdcm_expat_XML_GetIdAttributeIndex
#define XML_GetInputContext gdcm_expat_XML_GetInputContext
#define XML_GetSpecifiedAttributeCount gdcm_expat_XML_GetSpecifiedAttributeCount
#define XML_Parse gdcm_expat_XML_Parse
#define XML_ParseBuffer gdcm_expat_XML_ParseBuffer
#define XML_ParserCreate gdcm_expat_XML_ParserCreate
#define XML_ParserCreateNS gdcm_expat_XML_ParserCreateNS
#define XML_ParserCreate_MM gdcm_expat_XML_ParserCreate_MM
#define XML_ParserFree gdcm_expat_XML_ParserFree
#define XML_SetAttlistDeclHandler gdcm_expat_XML_SetAttlistDeclHandler
#define XML_SetBase gdcm_expat_XML_SetBase
#define XML_SetCdataSectionHandler gdcm_expat_XML_SetCdataSectionHandler
#define XML_SetCharacterDataHandler gdcm_expat_XML_SetCharacterDataHandler
#define XML_SetCommentHandler gdcm_expat_XML_SetCommentHandler
#define XML_SetDefaultHandler gdcm_expat_XML_SetDefaultHandler
#define XML_SetDefaultHandlerExpand gdcm_expat_XML_SetDefaultHandlerExpand
#define XML_SetDoctypeDeclHandler gdcm_expat_XML_SetDoctypeDeclHandler
#define XML_SetElementDeclHandler gdcm_expat_XML_SetElementDeclHandler
#define XML_SetElementHandler gdcm_expat_XML_SetElementHandler
#define XML_SetEncoding gdcm_expat_XML_SetEncoding
#define XML_SetEndCdataSectionHandler gdcm_expat_XML_SetEndCdataSectionHandler
#define XML_SetEndDoctypeDeclHandler gdcm_expat_XML_SetEndDoctypeDeclHandler
#define XML_SetEndElementHandler gdcm_expat_XML_SetEndElementHandler
#define XML_SetEndNamespaceDeclHandler gdcm_expat_XML_SetEndNamespaceDeclHandler
#define XML_SetEntityDeclHandler gdcm_expat_XML_SetEntityDeclHandler
#define XML_SetExternalEntityRefHandler gdcm_expat_XML_SetExternalEntityRefHandler
#define XML_SetExternalEntityRefHandlerArg gdcm_expat_XML_SetExternalEntityRefHandlerArg
#define XML_SetNamespaceDeclHandler gdcm_expat_XML_SetNamespaceDeclHandler
#define XML_SetNotStandaloneHandler gdcm_expat_XML_SetNotStandaloneHandler
#define XML_SetNotationDeclHandler gdcm_expat_XML_SetNotationDeclHandler
#define XML_SetParamEntityParsing gdcm_expat_XML_SetParamEntityParsing
#define XML_SetProcessingInstructionHandler gdcm_expat_XML_SetProcessingInstructionHandler
#define XML_SetReturnNSTriplet gdcm_expat_XML_SetReturnNSTriplet
#define XML_SetStartCdataSectionHandler gdcm_expat_XML_SetStartCdataSectionHandler
#define XML_SetStartDoctypeDeclHandler gdcm_expat_XML_SetStartDoctypeDeclHandler
#define XML_SetStartElementHandler gdcm_expat_XML_SetStartElementHandler
#define XML_SetStartNamespaceDeclHandler gdcm_expat_XML_SetStartNamespaceDeclHandler
#define XML_SetUnknownEncodingHandler gdcm_expat_XML_SetUnknownEncodingHandler
#define XML_SetUnparsedEntityDeclHandler gdcm_expat_XML_SetUnparsedEntityDeclHandler
#define XML_SetUserData gdcm_expat_XML_SetUserData
#define XML_SetXmlDeclHandler gdcm_expat_XML_SetXmlDeclHandler
#define XML_UseParserAsHandlerArg gdcm_expat_XML_UseParserAsHandlerArg
#define XmlGetUtf16InternalEncoding gdcm_expat_XmlGetUtf16InternalEncoding
#define XmlGetUtf16InternalEncodingNS gdcm_expat_XmlGetUtf16InternalEncodingNS
#define XmlGetUtf8InternalEncoding gdcm_expat_XmlGetUtf8InternalEncoding
#define XmlGetUtf8InternalEncodingNS gdcm_expat_XmlGetUtf8InternalEncodingNS
#define XmlInitEncoding gdcm_expat_XmlInitEncoding
#define XmlInitEncodingNS gdcm_expat_XmlInitEncodingNS
#define XmlInitUnknownEncoding gdcm_expat_XmlInitUnknownEncoding
#define XmlInitUnknownEncodingNS gdcm_expat_XmlInitUnknownEncodingNS
#define XmlParseXmlDecl gdcm_expat_XmlParseXmlDecl
#define XmlParseXmlDeclNS gdcm_expat_XmlParseXmlDeclNS
#define XmlSizeOfUnknownEncoding gdcm_expat_XmlSizeOfUnknownEncoding
#define XmlUtf16Encode gdcm_expat_XmlUtf16Encode
#define XmlUtf8Encode gdcm_expat_XmlUtf8Encode
#define XmlPrologStateInit gdcm_expat_XmlPrologStateInit
#define XmlPrologStateInitExternalEntity gdcm_expat_XmlPrologStateInitExternalEntity

#endif
