#!/bin/sh
../src/mpeg2enc/mpeg2encode test.par new.m2v
echo Verifying bitstream
cmp test.m2v new.m2v
../src/mpeg2dec/mpeg2decode -f -b new.m2v -o0 r%d
echo Comparing encoder and decoder output
cmp q0.Y r0.Y
cmp q1.Y r1.Y
cmp q2.Y r2.Y
cmp q0.U r0.U
cmp q1.U r1.U
cmp q2.U r2.U
cmp q0.V r0.V
cmp q1.V r1.V
cmp q2.V r2.V
echo Verifying decoder
../src/mpeg2dec/mpeg2decode -f -b test.m2v -o0 new%d
cmp recon0.Y new0.Y
cmp recon1.Y new1.Y
cmp recon2.Y new2.Y
cmp recon0.U new0.U
cmp recon1.U new1.U
cmp recon2.U new2.U
cmp recon0.V new0.V
cmp recon1.V new1.V
cmp recon2.V new2.V
echo Cleaning
rm -f new.m2v xyz stat.out new?.? q?.? r?.?
