// -*- C++ -*- generated by wxGlade 0.4.1 on Fri Aug  4 23:01:01 2006

#include <wx/wx.h>
#include <wx/image.h>
#include "MyFrame.h"



class MyApp: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
    wxInitAllImageHandlers();
    MyFrame* frame_1_gdcm = new MyFrame(0, -1, wxT(""));
    SetTopWindow(frame_1_gdcm);
    frame_1_gdcm->Show();
    return true;
}
