// -*- C++ -*- generated by wxGlade 0.4.1 on Sat Aug 19 15:12:57 2006

#include <wx/wx.h>
#include <wx/image.h>
#include "wxVTKRenderWindowInteractor.h"

#ifndef MYFRAME_H
#define MYFRAME_H

// begin wxGlade: ::dependencies
// end wxGlade


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxMenuBar* frame_1_menubar;
    wxStatusBar* frame_1_statusbar;
    wxToolBar* frame_1_toolbar;
    wxVTKRenderWindowInteractor* window_1;
    wxPanel* panel_1;
    // end wxGlade
}; // wxGlade: end class


#endif // MYFRAME_H
