// -*- C++ -*- generated by wxGlade 0.4.1 on Sat Aug 19 15:12:57 2006

#include "MyFrame.h"


MyFrame::MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MyFrame::MyFrame
    panel_1 = new wxPanel(this, -1);
    frame_1_menubar = new wxMenuBar();
    SetMenuBar(frame_1_menubar);
    wxMenu* wxglade_tmp_menu_1 = new wxMenu();
    wxglade_tmp_menu_1->Append(wxNewId(), wxT("Open"), wxT("Open DICOM file"), wxITEM_NORMAL);
    wxglade_tmp_menu_1->AppendSeparator();
    wxglade_tmp_menu_1->Append(wxNewId(), wxT("Exit"), wxT("Exit app"), wxITEM_NORMAL);
    frame_1_menubar->Append(wxglade_tmp_menu_1, wxT("File"));
    wxMenu* wxglade_tmp_menu_2 = new wxMenu();
    wxglade_tmp_menu_2->Append(wxNewId(), wxT("About"), wxT("About Dialog"), wxITEM_NORMAL);
    frame_1_menubar->Append(wxglade_tmp_menu_2, wxT("Help"));
    frame_1_statusbar = CreateStatusBar(1, 0);
    frame_1_toolbar = new wxToolBar(this, -1, wxDefaultPosition, wxDefaultSize, wxTB_HORIZONTAL|wxTB_TEXT);
    SetToolBar(frame_1_toolbar);
    frame_1_toolbar->AddTool(wxNewId(), wxT("tool"), wxNullBitmap, wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""));
    frame_1_toolbar->AddSeparator();
    frame_1_toolbar->AddTool(wxNewId(), wxT("tool"), wxNullBitmap, wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""));
    frame_1_toolbar->AddSeparator();
    frame_1_toolbar->AddTool(wxNewId(), wxT("tool"), wxNullBitmap, wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""));
    frame_1_toolbar->Realize();
    window_1 = new wxVTKRenderWindowInteractor(panel_1, -1);

    set_properties();
    do_layout();
    // end wxGlade
}


void MyFrame::set_properties()
{
    // begin wxGlade: MyFrame::set_properties
    SetTitle(wxT("wxGDCM"));
    SetSize(wxSize(436, 350));
    int frame_1_statusbar_widths[] = { -1 };
    frame_1_statusbar->SetStatusWidths(1, frame_1_statusbar_widths);
    const wxString frame_1_statusbar_fields[] = {
        wxT("frame_1_statusbar")
    };
    for(int i = 0; i < frame_1_statusbar->GetFieldsCount(); ++i) {
        frame_1_statusbar->SetStatusText(frame_1_statusbar_fields[i], i);
    }
    // end wxGlade
}


void MyFrame::do_layout()
{
    // begin wxGlade: MyFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxGridSizer* grid_sizer_1 = new wxGridSizer(1, 1, 0, 0);
    grid_sizer_1->Add(window_1, 1, wxEXPAND, 0);
    panel_1->SetAutoLayout(true);
    panel_1->SetSizer(grid_sizer_1);
    grid_sizer_1->Fit(panel_1);
    grid_sizer_1->SetSizeHints(panel_1);
    sizer_1->Add(panel_1, 1, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}

