// -*- C++ -*- generated by wxGlade 0.4.1 on Sat Aug 19 15:18:26 2006

#include <wx/wx.h>
#include <wx/image.h>

#ifndef WXGDCMFRAME_H
#define WXGDCMFRAME_H

// begin wxGlade: ::dependencies
// end wxGlade


class wxGDCMFrame: public wxFrame {
public:
    // begin wxGlade: wxGDCMFrame::ids
    // end wxGlade

    wxGDCMFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: wxGDCMFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: wxGDCMFrame::attributes
    wxMenuBar* frame_1_menubar;
    wxStatusBar* frame_1_statusbar;
    wxToolBar* frame_1_toolbar;
    wxVTKRenderWindowInteractor* window_1;
    wxPanel* panel_1;
    // end wxGlade
}; // wxGlade: end class


#endif // WXGDCMFRAME_H
