// -*- C++ -*- generated by wxGlade 0.4.1 on Sat Aug 19 15:28:55 2006

#include "wxGDCMFrame.h"


wxGDCMFrame::wxGDCMFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: wxGDCMFrame::wxGDCMFrame
    Panel = new wxPanel(this, -1);
    TopFrameMenubar = new wxMenuBar();
    SetMenuBar(TopFrameMenubar);
    wxMenu* wxglade_tmp_menu_1 = new wxMenu();
    wxglade_tmp_menu_1->Append(wxNewId(), wxT("Open"), wxT("Open DICOM file"), wxITEM_NORMAL);
    wxglade_tmp_menu_1->AppendSeparator();
    wxglade_tmp_menu_1->Append(wxNewId(), wxT("Exit"), wxT("Exit app"), wxITEM_NORMAL);
    TopFrameMenubar->Append(wxglade_tmp_menu_1, wxT("File"));
    wxMenu* wxglade_tmp_menu_2 = new wxMenu();
    wxglade_tmp_menu_2->Append(wxNewId(), wxT("About"), wxT("About Dialog"), wxITEM_NORMAL);
    TopFrameMenubar->Append(wxglade_tmp_menu_2, wxT("Help"));
    TopFrameStatusbar = CreateStatusBar(1, 0);
    TopFrameToolbar = new wxToolBar(this, -1, wxDefaultPosition, wxDefaultSize, wxTB_HORIZONTAL|wxTB_TEXT);
    SetToolBar(TopFrameToolbar);
    TopFrameToolbar->AddTool(wxNewId(), wxT("tool"), wxNullBitmap, wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""));
    TopFrameToolbar->AddSeparator();
    TopFrameToolbar->AddTool(wxNewId(), wxT("tool"), wxNullBitmap, wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""));
    TopFrameToolbar->AddSeparator();
    TopFrameToolbar->AddTool(wxNewId(), wxT("tool"), wxNullBitmap, wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""));
    TopFrameToolbar->Realize();
    VTKwindow = new wxVTKRenderWindowInteractor(Panel, -1);

    set_properties();
    do_layout();
    // end wxGlade
}


void wxGDCMFrame::set_properties()
{
    // begin wxGlade: wxGDCMFrame::set_properties
    SetTitle(wxT("wxGDCM"));
    SetSize(wxSize(436, 350));
    int TopFrameStatusbar_widths[] = { -1 };
    TopFrameStatusbar->SetStatusWidths(1, TopFrameStatusbar_widths);
    const wxString TopFrameStatusbar_fields[] = {
        wxT("frame_1_statusbar")
    };
    for(int i = 0; i < TopFrameStatusbar->GetFieldsCount(); ++i) {
        TopFrameStatusbar->SetStatusText(TopFrameStatusbar_fields[i], i);
    }
    // end wxGlade
}


void wxGDCMFrame::do_layout()
{
    // begin wxGlade: wxGDCMFrame::do_layout
    wxBoxSizer* Sizer = new wxBoxSizer(wxVERTICAL);
    wxGridSizer* GridSizer = new wxGridSizer(1, 1, 0, 0);
    GridSizer->Add(VTKwindow, 1, wxEXPAND, 0);
    Panel->SetAutoLayout(true);
    Panel->SetSizer(GridSizer);
    GridSizer->Fit(Panel);
    GridSizer->SetSizeHints(Panel);
    Sizer->Add(Panel, 1, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(Sizer);
    Layout();
    // end wxGlade
}

