# apt-get install mono-jit mono-mcs mono-gac mono-gmcs

FIND_PROGRAM(MONO_EXECUTABLE mono)
FIND_PROGRAM(MCS_EXECUTABLE mcs)
FIND_PROGRAM(GMCS_EXECUTABLE gmcs)
FIND_PROGRAM(GACUTIL_EXECUTABLE gacutil)

MARK_AS_ADVANCED(MONO_EXECUTABLE MCS_EXECUTABLE GMCS_EXECUTABLE GACUTIL_EXECUTABLE)
